#version 450

#define MAX_LIGHTS 32

struct Light {
    vec3 position;
    vec3 color;
    float intensity;
    int type;
};

layout(location = 0) in vec3 fragColor;
layout(location = 1) in vec2 fragUV;
layout(location = 2) in vec3 fragNormal;
layout(location = 3) in vec3 fragPos;
layout(location = 4) in vec3 fragGouraudColor;    // Sun
layout(location = 5) in vec4 fragPosLightSpace;
layout(location = 6) in vec3 fragOtherLightColor; // Moon

layout(set = 0, binding = 0) uniform UniformBufferObject {
    mat4 view;
    mat4 proj;
    vec3 viewPos;
    mat4 lightSpaceMatrix;
    Light lights[MAX_LIGHTS];
    int numLights;
} ubo;

layout(push_constant) uniform PushConstantObject {
    mat4 model;
    int shadingMode;
} pco;

layout(set = 0, binding = 1) uniform sampler2D shadowMap;
layout(set = 1, binding = 0) uniform sampler2D texSampler;

layout(location = 0) out vec4 outColor;

float ShadowCalculation(vec4 fragPosLightSpace) {
    vec3 projCoords = fragPosLightSpace.xyz / fragPosLightSpace.w;
    projCoords.xy = projCoords.xy * 0.5 + 0.5;
    
    float currentDepth = projCoords.z;

    if(projCoords.z > 1.0 || projCoords.z < 0.0) return 0.0;
    if(projCoords.x < 0.0 || projCoords.x > 1.0 || projCoords.y < 0.0 || projCoords.y > 1.0) return 0.0;

    float bias = 0.005;
    float shadow = 0.0;
    vec2 texelSize = 1.0 / textureSize(shadowMap, 0);
    
    for(int x = -1; x <= 1; ++x) {
        for(int y = -1; y <= 1; ++y) {
            float pcfDepth = texture(shadowMap, projCoords.xy + vec2(x, y) * texelSize).r;
            shadow += currentDepth - bias > pcfDepth ? 1.0 : 0.0;
        }    
    }
    shadow /= 9.0;
    
    return shadow;
}

void main() {
    vec4 texColor = texture(texSampler, fragUV);
    vec3 lighting = vec3(0.0);
    
    // Calculate shadow map value (This map is generated by the Sun)
    float shadow = ShadowCalculation(fragPosLightSpace);

    if (pco.shadingMode == 0) {
        // Gouraud: Only shadow the Sun component. Add Moon component directly.
        lighting = fragGouraudColor * (1.0 - shadow) + fragOtherLightColor;
    } else {
        // Phong: Calculate per pixel
        vec3 normal = normalize(fragNormal);
        vec3 viewDir = normalize(ubo.viewPos - fragPos);

        for(int i = 0; i < ubo.numLights; i++) {
            // Ambient
            float ambientStrength = 0.1;
            vec3 ambient = ambientStrength * ubo.lights[i].color * ubo.lights[i].intensity;

            // Diffuse
            vec3 lightDir = normalize(ubo.lights[i].position - fragPos);
            float diff = max(dot(normal, lightDir), 0.0);
            vec3 diffuse = diff * ubo.lights[i].color * ubo.lights[i].intensity;

            // Specular
            float specularStrength = 0.5;
            vec3 reflectDir = reflect(-lightDir, normal);
            float spec = pow(max(dot(viewDir, reflectDir), 0.0), 32);
            vec3 specular = specularStrength * spec * ubo.lights[i].color * ubo.lights[i].intensity;

            // Shadow Logic: Apply shadow ONLY to Light 0 (Sun)
            float lightShadow = 0.0;
            if (i == 0) {
                lightShadow = shadow;
            }

            lighting += (ambient + (1.0 - lightShadow) * (diffuse + specular));
        }
    }

    outColor = vec4(lighting * texColor.rgb, texColor.a);
}